BASE_URL = 'https://github.com/nflverse/nflfastR-data/releases/download/play_by_play_{year}.csv.gz?raw=True'
ROSTER_URL = 'https://raw.githubusercontent.com/nflverse/nflfastR-roster/releases/download/seasons/roster_{year}.csv'
DEPTH_CHART_URL = 'https://github.com/nflverse/nflfastR-roster/releases/download/data/seasons/depth_charts_{year}.csv.gz?raw=True'
INJURY_URL = 'https://github.com/nflverse/nflfastR-roster/blob/releases/download/seasons/injuries_{year}.csv.gz?raw=True'
TEAM_LOGO_URL = 'https://raw.githubusercontent.com/nflverse/nflfastR-data/releases/download/teams_colors_logos.csv'
SCHEDULE_URL = 'https://github.com/nflverse/nflfastR-data/releases/download/schedules/sched_{year}.rds?raw=True'
